### ISSUE TITLE
Libraries for viewing and reading written alt

### ISSUE THREAD

**Issue by LindseyB** [LindseyB/readable-alt#2]
```[tasklist]
### Tasks
- [ ] Library for reading via ruby
- [ ] Library for reading via python
- [ ] Library for reading via js
- [ ] Move all libraries into their own
```

**Comment by LindseyB** [comment]
Libraries should be in their own repos and not shared
